//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.3649
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exportador_Ventas_ServP.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El Pino")]
        public string nombreEDS {
            get {
                return ((string)(this["nombreEDS"]));
            }
            set {
                this["nombreEDS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Calle 73 # 12 - 98")]
        public string Direccion {
            get {
                return ((string)(this["Direccion"]));
            }
            set {
                this["Direccion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DIESEL")]
        public string NombreDiesel {
            get {
                return ((string)(this["NombreDiesel"]));
            }
            set {
                this["NombreDiesel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SUPER")]
        public string NombreSuper {
            get {
                return ((string)(this["NombreSuper"]));
            }
            set {
                this["NombreSuper"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CORRIENTE")]
        public string NombreCorriente {
            get {
                return ((string)(this["NombreCorriente"]));
            }
            set {
                this["NombreCorriente"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0901")]
        public string CentroCostos {
            get {
                return ((string)(this["CentroCostos"]));
            }
            set {
                this["CentroCostos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>1,2</string>\r\n  <string>3,4</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection grupoIsla {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["grupoIsla"]));
            }
            set {
                this["grupoIsla"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("830.051.180-7")]
        public string NITEDS {
            get {
                return ((string)(this["NITEDS"]));
            }
            set {
                this["NITEDS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3107855")]
        public string telefonoEDS {
            get {
                return ((string)(this["telefonoEDS"]));
            }
            set {
                this["telefonoEDS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4731")]
        public string codigoCIIU {
            get {
                return ((string)(this["codigoCIIU"]));
            }
            set {
                this["codigoCIIU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-2000")]
        public double DiferenciaSaldoDisposicion {
            get {
                return ((double)(this["DiferenciaSaldoDisposicion"]));
            }
            set {
                this["DiferenciaSaldoDisposicion"] = value;
            }
        }
    }
}
